Repository Sanchitbajaj02/CppPrograms, pull requests merged in 2021-10, with the labels that each got.

#63 Stack using Array
  Stack Using Array.cpp
Labels: hacktoberfest-accepted

#75 Delete a word from string.cpp
  Delete a word from string.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#77 Create tree_traversal.cpp
  tree_traversal.cpp
Labels: hacktoberfest, beginner, hacktoberfest-accepted

#78 snake water gun game
  Snake_Water_gun_Game.cpp
Labels: hacktoberfest, beginner, hacktoberfest-accepted

#76 Delete the middle node of a Linked List.cpp
  Delete the middle node of a Linked List.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#80 Armstrong number.cpp
  Armstrong number.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#81 Create Count number of digits.cpp
  Count number of digits.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#82 StringDetails.cpp
  StringDetails.cpp
Labels: hacktoberfest, hacktoberfest-accepted
